### ISSUE TITLE
story_arc_list Results Failing Due to type_error for publisher field : none.not_allowed

### ISSUE THREAD

**Issue by themadman0980** [Metron-Project/Simyan#118]
As per the title. I'm getting lots of validation errors in the following format:

```
1 validation error for ParsingModel[List[simyan.schemas.story_arc.StoryArc]]
__root__ -> 0 -> publisher
none is not an allowed value (type=type_error.none.not_allowed)
```

I have had a one-off similar occurrence of a failure due to lack of value for 'first_appeared_in_issue' when doing a filter by name search for 'Lo, this Monster'.

The code which is triggering this issue:
`            results = _cvSession.story_arc_list(params={"filter": "name:%s" % (name)})`

**Comment by Buried-In-Code** [comment]
Thanks for raising this, I'll get the StoryArc.Publisher field updated to be Optional
