### ISSUE TITLE
[BUG] no such column: query_date

### ISSUE THREAD

**Issue by zachstultz** [Metron-Project/Simyan#175]
Keep getting 
```no such column: query_date``` 
error when trying to search comic vine, using the latest 1.2.0 version as well. Double checked my api_key value as well and it's good.

```python
session = Comicvine(api_key=api_key, cache=SQLiteCache())
```

**Comment by Buried-In-Code** [comment]
That appears to be an issue with the cache, you should just need to delete the cache file, which is located in `{HOME}/.cache/simyan`.
I did a rework of the cache in v0.13.0, so if you've updated from a previous version that'll be why.

Let me know if you have any other issues

**Comment by zachstultz** [comment]
Fixed with no cache, apologies for the confusion, I genuinely thought it was a bug at first.
